import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1765970501456 implements MigrationInterface {
    name = 'InitialSchema1765970501456'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "permissions" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" SERIAL NOT NULL, "userId" uuid NOT NULL, "roleId" integer NOT NULL, "assignedAt" TIMESTAMP NOT NULL, "assignedBy" character varying, CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_88481b0c4ed9ada47e9fdd6747" ON "user_roles" ("userId", "roleId") `);
        await queryRunner.query(`CREATE TYPE "public"."amendment_votes_vote_enum" AS ENUM('approve', 'reject', 'abstain')`);
        await queryRunner.query(`CREATE TABLE "amendment_votes" ("id" SERIAL NOT NULL, "amendment_id" character varying NOT NULL, "voter_id" character varying NOT NULL, "vote" "public"."amendment_votes_vote_enum" NOT NULL, "comment" character varying, "voted_at" TIMESTAMP NOT NULL DEFAULT now(), "amendmentId" uuid, "voterId" uuid, CONSTRAINT "UQ_47c56d0c1436bfd6dc74795f5ee" UNIQUE ("amendment_id", "voter_id"), CONSTRAINT "PK_2d792a8298f6c8bb7b22b6182bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0943632be20adedc064988c36a" ON "amendment_votes" ("voter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_14e8937b95874fc6ef52d80a19" ON "amendment_votes" ("amendment_id") `);
        await queryRunner.query(`CREATE TYPE "public"."amendments_type_enum" AS ENUM('addition', 'modification', 'removal')`);
        await queryRunner.query(`CREATE TYPE "public"."amendments_status_enum" AS ENUM('proposed', 'under_review', 'approved', 'rejected', 'implemented')`);
        await queryRunner.query(`CREATE TABLE "amendments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text NOT NULL, "type" "public"."amendments_type_enum" NOT NULL, "changes" jsonb NOT NULL DEFAULT '[]', "status" "public"."amendments_status_enum" NOT NULL DEFAULT 'proposed', "proposed_by_id" character varying NOT NULL, "proposed_at" TIMESTAMP NOT NULL, "voting_starts_at" TIMESTAMP, "voting_ends_at" TIMESTAMP, "implemented_at" TIMESTAMP, "migrationPlan" character varying, "proposedById" uuid, CONSTRAINT "PK_232751b4529e81fd8a6b2847ace" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_237ece008b3654cb987e693982" ON "amendments" ("proposed_by_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d02eaaf2cecca4c46dbfc41ecc" ON "amendments" ("proposed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4231164039b4a82a7b932295bb" ON "amendments" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."compliance_issues_severity_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."compliance_issues_status_enum" AS ENUM('open', 'in_progress', 'resolved', 'ignored')`);
        await queryRunner.query(`CREATE TABLE "compliance_issues" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "check_id" character varying NOT NULL, "severity" "public"."compliance_issues_severity_enum" NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "remediationSteps" character varying, "status" "public"."compliance_issues_status_enum" NOT NULL DEFAULT 'open', "assigned_to" character varying, "resolved_at" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "checkId" uuid, CONSTRAINT "PK_9d1f18c69bd0346528ac3564521" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4eb08da845cc47276f2fdcf3b9" ON "compliance_issues" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5dcc8a2873d1cb66dc198f6d09" ON "compliance_issues" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_214b01a4cee4276844b39eb41c" ON "compliance_issues" ("severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_a855a6da18099b1b92d208615e" ON "compliance_issues" ("check_id") `);
        await queryRunner.query(`CREATE TYPE "public"."compliance_checks_status_enum" AS ENUM('passed', 'failed', 'warning', 'pending')`);
        await queryRunner.query(`CREATE TABLE "compliance_checks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entity_type" character varying NOT NULL, "entity_id" character varying NOT NULL, "check_type" character varying NOT NULL, "status" "public"."compliance_checks_status_enum" NOT NULL, "results" jsonb, "notes" text, "performed_by_id" character varying NOT NULL, "performed_at" TIMESTAMP NOT NULL, "performedById" uuid, CONSTRAINT "PK_e64798895fdb89aaef6ca4595a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1efd1028c207c8a3dc5422ecff" ON "compliance_checks" ("performed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b6ad26843cef20c74c0b14580f" ON "compliance_checks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3e6864954de485119aa65b698" ON "compliance_checks" ("check_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e81c896f25d6052c4337eb2cc" ON "compliance_checks" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "name" character varying NOT NULL, "avatar" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_currency_enum" AS ENUM('USD', 'EUR', 'GBP', 'JPY')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed', 'cancelled', 'refunded')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_paymentmethod_enum" AS ENUM('credit_card', 'debit_card', 'paypal', 'stripe', 'bank_transfer')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" "public"."payments_currency_enum" NOT NULL DEFAULT 'USD', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "paymentMethod" "public"."payments_paymentmethod_enum" NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}', "payment_intent_id" character varying, "transaction_id" character varying, "failure_reason" text, "processed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "retry_count" integer NOT NULL DEFAULT '0', "max_retries" integer NOT NULL DEFAULT '3', "next_retry_at" TIMESTAMP, "refund_amount" numeric(10,2), "refund_reason" text, "refunded_at" TIMESTAMP, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0bd2a15bde4058590f0caea36b" ON "payments" ("payment_intent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1237daf748b7653a6ebb9492fe" ON "payments" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_427785468fb7d2733f59e7d7d3" ON "payments" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "principle_versions" ("id" SERIAL NOT NULL, "principleId" uuid NOT NULL, "version" character varying NOT NULL, "title" text NOT NULL, "description" text NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}', "changeLog" character varying NOT NULL, "authorId" character varying NOT NULL, "effectiveDate" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1007cab518d01d5b512affae505" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7dbe35cd912293d3796821d1ba" ON "principle_versions" ("version") `);
        await queryRunner.query(`CREATE INDEX "IDX_29146cab921f62ed4a1d0a4d60" ON "principle_versions" ("principleId") `);
        await queryRunner.query(`CREATE TABLE "performance_standards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "principleId" uuid NOT NULL, "name" character varying NOT NULL, "endpointType" character varying NOT NULL, "targetResponseTime" integer NOT NULL, "metricType" character varying NOT NULL, "concurrentUsers" integer NOT NULL, "additionalMetrics" jsonb NOT NULL DEFAULT '{}', "description" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6deae97eb2db0041aded93dea70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e46ea663fee4d6e44ca20affa6" ON "performance_standards" ("endpointType", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_a50f9d0a4f4705f19644bddaaf" ON "performance_standards" ("principleId") `);
        await queryRunner.query(`CREATE TABLE "load_test_requirements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "principleId" uuid NOT NULL, "name" character varying NOT NULL, "testType" character varying NOT NULL, "endpointPattern" character varying NOT NULL, "testParameters" jsonb NOT NULL DEFAULT '{"rampUp":{"from":0,"to":100,"duration":"5m"}}', "expectedRate" integer NOT NULL, "maxResponseTime" integer NOT NULL, "maxErrorRate" integer NOT NULL, "scriptPath" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6bf97dfa35258c42701afdfdaad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_66206c0847a451fc2c4804463e" ON "load_test_requirements" ("testType") `);
        await queryRunner.query(`CREATE INDEX "IDX_90f4b63bae581fc89a38f2604f" ON "load_test_requirements" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad9488d9b3a94525019c455574" ON "load_test_requirements" ("principleId") `);
        await queryRunner.query(`CREATE TYPE "public"."governance_rules_ruletype_enum" AS ENUM('amendment', 'compliance', 'approval', 'enforcement')`);
        await queryRunner.query(`CREATE TABLE "governance_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "principleId" uuid NOT NULL, "ruleType" "public"."governance_rules_ruletype_enum" NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "parameters" jsonb NOT NULL DEFAULT '{}', "isActive" boolean NOT NULL DEFAULT true, "effectiveFrom" TIMESTAMP, "effectiveTo" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a6e7e2ca0f98b8e1e356ef3440e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d72843c83b7d4ff839caa99555" ON "governance_rules" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_68d1e4da2dc78e41886fe67238" ON "governance_rules" ("ruleType") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2879a6fe06cd063f962d45aba" ON "governance_rules" ("principleId") `);
        await queryRunner.query(`CREATE TABLE "principles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "priority" integer NOT NULL DEFAULT '1', "metadata" jsonb NOT NULL DEFAULT '{"category":"","tags":[],"relatedPrinciples":[],"examples":[]}', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "currentVersion" character varying NOT NULL DEFAULT '1.0.0', CONSTRAINT "UQ_9e71dbd943b69615ac7e2f09f6f" UNIQUE ("slug"), CONSTRAINT "PK_f6ffb163eac4b074b948a66b0d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_01f559acbabaf490f3a9391c04" ON "principles" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_444ce49d21576331f17168f12b" ON "principles" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e71dbd943b69615ac7e2f09f6" ON "principles" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."quality_gates_type_enum" AS ENUM('automated', 'manual')`);
        await queryRunner.query(`CREATE TABLE "quality_gates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "principleId" uuid NOT NULL, "name" character varying NOT NULL, "type" "public"."quality_gates_type_enum" NOT NULL, "tool" character varying, "requirement" text NOT NULL, "criteria" jsonb NOT NULL DEFAULT '{}', "isRequired" boolean NOT NULL DEFAULT true, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b74904cfefb353de2a94552e49e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b86dc6143f4ecbb46384628931" ON "quality_gates" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed05946c7999d4c70f9a096785" ON "quality_gates" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fc2e76ddfcb79d008179098e4" ON "quality_gates" ("principleId") `);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_472b25323af01488f1f66a06b67" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_86033897c009fcca8b6505d6be2" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "amendment_votes" ADD CONSTRAINT "FK_b16a0aecb71a28866cba5568c98" FOREIGN KEY ("amendmentId") REFERENCES "amendments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "amendment_votes" ADD CONSTRAINT "FK_9d28377cf027b97e1ca73459464" FOREIGN KEY ("voterId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "amendments" ADD CONSTRAINT "FK_fabbb72aa00cac519dd452d5d58" FOREIGN KEY ("proposedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "compliance_issues" ADD CONSTRAINT "FK_6f61efb8329d453b07630d5c6ca" FOREIGN KEY ("checkId") REFERENCES "compliance_checks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "compliance_checks" ADD CONSTRAINT "FK_24ccc494fa622bd11febcbe92cf" FOREIGN KEY ("performedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "principle_versions" ADD CONSTRAINT "FK_29146cab921f62ed4a1d0a4d600" FOREIGN KEY ("principleId") REFERENCES "principles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "performance_standards" ADD CONSTRAINT "FK_a50f9d0a4f4705f19644bddaaf7" FOREIGN KEY ("principleId") REFERENCES "principles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "load_test_requirements" ADD CONSTRAINT "FK_ad9488d9b3a94525019c4555746" FOREIGN KEY ("principleId") REFERENCES "principles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "governance_rules" ADD CONSTRAINT "FK_c2879a6fe06cd063f962d45aba4" FOREIGN KEY ("principleId") REFERENCES "principles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_gates" ADD CONSTRAINT "FK_0fc2e76ddfcb79d008179098e40" FOREIGN KEY ("principleId") REFERENCES "principles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "quality_gates" DROP CONSTRAINT "FK_0fc2e76ddfcb79d008179098e40"`);
        await queryRunner.query(`ALTER TABLE "governance_rules" DROP CONSTRAINT "FK_c2879a6fe06cd063f962d45aba4"`);
        await queryRunner.query(`ALTER TABLE "load_test_requirements" DROP CONSTRAINT "FK_ad9488d9b3a94525019c4555746"`);
        await queryRunner.query(`ALTER TABLE "performance_standards" DROP CONSTRAINT "FK_a50f9d0a4f4705f19644bddaaf7"`);
        await queryRunner.query(`ALTER TABLE "principle_versions" DROP CONSTRAINT "FK_29146cab921f62ed4a1d0a4d600"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "compliance_checks" DROP CONSTRAINT "FK_24ccc494fa622bd11febcbe92cf"`);
        await queryRunner.query(`ALTER TABLE "compliance_issues" DROP CONSTRAINT "FK_6f61efb8329d453b07630d5c6ca"`);
        await queryRunner.query(`ALTER TABLE "amendments" DROP CONSTRAINT "FK_fabbb72aa00cac519dd452d5d58"`);
        await queryRunner.query(`ALTER TABLE "amendment_votes" DROP CONSTRAINT "FK_9d28377cf027b97e1ca73459464"`);
        await queryRunner.query(`ALTER TABLE "amendment_votes" DROP CONSTRAINT "FK_b16a0aecb71a28866cba5568c98"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_86033897c009fcca8b6505d6be2"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_472b25323af01488f1f66a06b67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fc2e76ddfcb79d008179098e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed05946c7999d4c70f9a096785"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b86dc6143f4ecbb46384628931"`);
        await queryRunner.query(`DROP TABLE "quality_gates"`);
        await queryRunner.query(`DROP TYPE "public"."quality_gates_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e71dbd943b69615ac7e2f09f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_444ce49d21576331f17168f12b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01f559acbabaf490f3a9391c04"`);
        await queryRunner.query(`DROP TABLE "principles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2879a6fe06cd063f962d45aba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68d1e4da2dc78e41886fe67238"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d72843c83b7d4ff839caa99555"`);
        await queryRunner.query(`DROP TABLE "governance_rules"`);
        await queryRunner.query(`DROP TYPE "public"."governance_rules_ruletype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad9488d9b3a94525019c455574"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90f4b63bae581fc89a38f2604f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66206c0847a451fc2c4804463e"`);
        await queryRunner.query(`DROP TABLE "load_test_requirements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a50f9d0a4f4705f19644bddaaf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e46ea663fee4d6e44ca20affa6"`);
        await queryRunner.query(`DROP TABLE "performance_standards"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29146cab921f62ed4a1d0a4d60"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7dbe35cd912293d3796821d1ba"`);
        await queryRunner.query(`DROP TABLE "principle_versions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_427785468fb7d2733f59e7d7d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1237daf748b7653a6ebb9492fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bd2a15bde4058590f0caea36b"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_currency_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e81c896f25d6052c4337eb2cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3e6864954de485119aa65b698"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6ad26843cef20c74c0b14580f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1efd1028c207c8a3dc5422ecff"`);
        await queryRunner.query(`DROP TABLE "compliance_checks"`);
        await queryRunner.query(`DROP TYPE "public"."compliance_checks_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a855a6da18099b1b92d208615e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_214b01a4cee4276844b39eb41c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5dcc8a2873d1cb66dc198f6d09"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4eb08da845cc47276f2fdcf3b9"`);
        await queryRunner.query(`DROP TABLE "compliance_issues"`);
        await queryRunner.query(`DROP TYPE "public"."compliance_issues_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."compliance_issues_severity_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4231164039b4a82a7b932295bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d02eaaf2cecca4c46dbfc41ecc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_237ece008b3654cb987e693982"`);
        await queryRunner.query(`DROP TABLE "amendments"`);
        await queryRunner.query(`DROP TYPE "public"."amendments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."amendments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14e8937b95874fc6ef52d80a19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0943632be20adedc064988c36a"`);
        await queryRunner.query(`DROP TABLE "amendment_votes"`);
        await queryRunner.query(`DROP TYPE "public"."amendment_votes_vote_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88481b0c4ed9ada47e9fdd6747"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
